# Generated by Django 2.2.4 on 2023-01-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
